from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Admin)
admin.site.register(University)
# admin.site.register(UniversityApproval)
admin.site.register(UniversityLogin)
admin.site.register(Instructor)
# admin.site.register(InstructorApproval)
admin.site.register(InstructorLogin)
admin.site.register(UniversityLogout)
# admin.site.register(ResearchRepository)
# admin.site.register(ResearchDocumentUpload)
admin.site.register(ResearchDocument)
# admin.site.register(ResearchDocumentUploadError)
admin.site.register(ResearchDocumentParseText)
admin.site.register(ResearchDocumentReferences)
admin.site.register(ResearchDocumentParseError)
# admin.site.register(ResearchDocumentSectionTokens)
admin.site.register(ResearchDocumentBasicStats)
admin.site.register(ResearchDocumentImages)
admin.site.register(ResearchDocumentEnhancedText)
admin.site.register(ResearchDocumentTextVector)
# admin.site.register(CheckingDocumentUpload)
admin.site.register(CheckingDocument)
admin.site.register(CheckingDocumentUploadError)
admin.site.register(CheckingDocumentParseText)
admin.site.register(CheckingDocumentReferences)
admin.site.register(CheckingDocumentParseError)
# admin.site.register(CheckingDocumentSectionTokens)
admin.site.register(CheckingDocumentBasicStats)
admin.site.register(CheckingDocumentEnhancedText)
admin.site.register(CheckingDocumentTextVector)
admin.site.register(CheckingDocumentCheckingProcess)
admin.site.register(CheckingDocumentReport)