# Generated by Django 5.2.6 on 2025-09-18 11:48

import detection.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checking_document_name', models.CharField(max_length=500)),
                ('checking_document_path', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckingDocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checking_document_name', models.CharField(max_length=500)),
                ('checking_document_path', models.CharField(max_length=1000)),
                ('is_upload_complete', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('certificate', models.FileField(upload_to=detection.models.Instructor.certificate_directory_path)),
                ('field', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_document_name', models.CharField(max_length=500)),
                ('research_document_path', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchDocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_document_name', models.CharField(max_length=255)),
                ('reseach_document_path', models.CharField(max_length=1000)),
                ('is_upload_complete', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('university_certificate', models.FileField(upload_to=detection.models.University.certificate_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckingDocumentBasicStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_references', models.IntegerField()),
                ('no_of_sentences', models.IntegerField()),
                ('no_of_characters', models.IntegerField()),
                ('no_of_words', models.IntegerField()),
                ('size_of_document', models.IntegerField()),
                ('no_of_images', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('checking_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.checkingdocument')),
            ],
        ),
        migrations.CreateModel(
            name='CheckingDocumentEnhancedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_index', models.IntegerField()),
                ('sentence_enhanced_text', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('checking_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.checkingdocument')),
            ],
        ),
        migrations.CreateModel(
            name='CheckingDocumentParseError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parse_text', models.TextField(max_length=50000)),
                ('error_message', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('checking_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.checkingdocument')),
            ],
        ),
        migrations.CreateModel(
            name='CheckingDocumentParseText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parse_text', models.TextField(max_length=50000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('checking_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.checkingdocument')),
            ],
        ),
        migrations.CreateModel(
            name='CheckingDocumentReferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=-1)),
                ('reference_text', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('checking_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.checkingdocument')),
            ],
        ),
        migrations.CreateModel(
            name='CheckingDocumentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_result', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('checking_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.checkingdocument')),
            ],
        ),
        migrations.CreateModel(
            name='CheckingDocumentSectionTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_index', models.IntegerField()),
                ('section_title', models.CharField(max_length=1000)),
                ('section_description', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('checking_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.checkingdocument')),
            ],
        ),
        migrations.CreateModel(
            name='CheckingDocumentTextVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_vector', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('checking_document_enhanced_text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.checkingdocumentenhancedtext')),
                ('checking_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.checkingdocument')),
            ],
        ),
        migrations.AddField(
            model_name='checkingdocument',
            name='checking_document_upload_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.checkingdocumentupload'),
        ),
        migrations.CreateModel(
            name='CheckingDocumentUploadError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('checking_document_upload_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.checkingdocumentupload')),
            ],
        ),
        migrations.AddField(
            model_name='checkingdocument',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.instructor'),
        ),
        migrations.CreateModel(
            name='ResearchDocumentBasicStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_references', models.IntegerField()),
                ('no_of_sentences', models.IntegerField()),
                ('no_of_characters', models.IntegerField()),
                ('no_of_words', models.IntegerField()),
                ('size_of_document', models.IntegerField()),
                ('no_of_images', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('research_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.researchdocument')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchDocumentEnhancedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_index', models.IntegerField()),
                ('sentence_enhanced_text', models.TextField(max_length=50000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('research_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.researchdocument')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchDocumentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('research_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.researchdocument')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchDocumentParseError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parse_text', models.TextField(max_length=50000)),
                ('error_message', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('research_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.researchdocument')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchDocumentReferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=-1)),
                ('reference_text', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('research_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.researchdocument')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchDocumentSectionTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_index', models.IntegerField()),
                ('section_title', models.CharField(max_length=1000)),
                ('section_description', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('research_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.researchdocument')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchDocumentTextVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_document_enhanced_text_id', models.IntegerField()),
                ('text_vector', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('research_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.researchdocument')),
            ],
        ),
        migrations.CreateModel(
            name='CheckingDocumentCheckingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('checking_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.checkingdocument')),
                ('checking_document_text_vector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.checkingdocumenttextvector')),
                ('research_document_text_vector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.researchdocumenttextvector')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchDocumentParseText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parse_text', models.TextField(max_length=50000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('research_document_upload_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.researchdocumentupload')),
            ],
        ),
        migrations.AddField(
            model_name='researchdocument',
            name='research_document_upload_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.researchdocumentupload'),
        ),
        migrations.CreateModel(
            name='ResearchDocumentUploadError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('research_document_upload_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.researchdocumentupload')),
            ],
        ),
        migrations.AddField(
            model_name='researchdocumentupload',
            name='research_repository_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.researchrepository'),
        ),
        migrations.AddField(
            model_name='researchdocument',
            name='research_repository_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.researchrepository'),
        ),
        migrations.AddField(
            model_name='researchrepository',
            name='university_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.university'),
        ),
        migrations.AddField(
            model_name='researchdocument',
            name='university_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.university'),
        ),
        migrations.CreateModel(
            name='InstructorApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.university')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='university_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.university'),
        ),
        migrations.CreateModel(
            name='UniversityApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.admin')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityLogout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.university')),
            ],
        ),
    ]
