# Generated by Django 5.2.7 on 2025-10-27 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_university_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorapproval',
            name='instructor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='detection.instructor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universityapproval',
            name='university_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='detection.university'),
            preserve_default=False,
        ),
    ]
