# Generated by Django 5.2.7 on 2025-10-28 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_instructorapproval_instructor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchdocumentparsetext',
            name='research_document_upload_id',
        ),
        migrations.RemoveField(
            model_name='researchdocument',
            name='research_document_upload_id',
        ),
        migrations.RemoveField(
            model_name='researchdocumentuploaderror',
            name='research_document_upload_id',
        ),
        migrations.RemoveField(
            model_name='researchrepository',
            name='university_id',
        ),
        migrations.RemoveField(
            model_name='researchdocument',
            name='research_repository_id',
        ),
        migrations.AddField(
            model_name='researchdocument',
            name='is_upload_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='researchdocumentparsetext',
            name='research_document_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='detection.researchdocument'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ResearchDocumentUpload',
        ),
        migrations.DeleteModel(
            name='ResearchDocumentUploadError',
        ),
        migrations.DeleteModel(
            name='ResearchRepository',
        ),
    ]
