# Generated by Django 5.2.7 on 2025-10-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_remove_researchdocumentparsetext_research_document_upload_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchdocumentparseerror',
            old_name='research_document',
            new_name='research_document_id',
        ),
    ]
