# Generated by Django 5.2.7 on 2025-10-28 18:47

import detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_rename_research_document_researchdocumentparseerror_research_document_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkingdocument',
            name='checking_document_path',
        ),
        migrations.RemoveField(
            model_name='researchdocument',
            name='research_document_path',
        ),
        migrations.AddField(
            model_name='checkingdocument',
            name='checking_document_file',
            field=models.FileField(default=1, upload_to=detection.models.CheckingDocument.research_document_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchdocument',
            name='research_document_file',
            field=models.FileField(default=1, upload_to=detection.models.ResearchDocument.research_document_directory_path),
            preserve_default=False,
        ),
    ]
