# Generated by Django 5.2.7 on 2025-10-29 02:37

import detection.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_remove_checkingdocument_checking_document_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkingdocument',
            name='checking_document_file',
            field=models.FileField(upload_to=detection.models.CheckingDocument.research_document_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='researchdocument',
            name='research_document_file',
            field=models.FileField(upload_to=detection.models.ResearchDocument.research_document_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
