# Generated by Django 5.2.7 on 2025-10-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_alter_checkingdocument_checking_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchdocument',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
