# Generated by Django 5.2.7 on 2025-10-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0008_researchdocument_is_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchdocumentimages',
            name='image_path',
        ),
        migrations.AddField(
            model_name='researchdocumentimages',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
