# Generated by Django 5.2.7 on 2025-10-29 10:08

import detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0009_remove_researchdocumentimages_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchdocumentimages',
            name='image',
            field=models.FileField(upload_to=detection.models.ResearchDocumentImages.research_document_directory_image_path),
        ),
    ]
