# Generated by Django 5.2.7 on 2025-10-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0010_alter_researchdocumentimages_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResearchDocumentSectionTokens',
        ),
    ]
