# Generated by Django 5.2.7 on 2025-10-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0011_delete_researchdocumentsectiontokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchdocumentreferences',
            name='reference_text',
            field=models.CharField(max_length=20000),
        ),
    ]
