# Generated by Django 5.2.7 on 2025-10-30 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0012_alter_researchdocumentreferences_reference_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchdocumenttextvector',
            name='research_document_enhanced_text_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.researchdocumentenhancedtext'),
        ),
    ]
