# Generated by Django 5.2.7 on 2025-10-30 09:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0013_alter_researchdocumenttextvector_research_document_enhanced_text_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchdocumenttextvector',
            name='text_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
