# Generated by Django 5.2.7 on 2025-10-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0014_alter_researchdocumenttextvector_text_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchdocumentreferences',
            name='reference_text',
            field=models.CharField(max_length=50000),
        ),
    ]
