# Generated by Django 5.2.7 on 2025-10-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0015_alter_researchdocumentreferences_reference_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityapproval',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='universityapproval',
            name='university_id',
        ),
        migrations.AddField(
            model_name='instructor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='InstructorApproval',
        ),
        migrations.DeleteModel(
            name='UniversityApproval',
        ),
    ]
