# Generated by Django 5.2.7 on 2025-11-01 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0016_remove_universityapproval_admin_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkingdocument',
            name='checking_document_upload_id',
        ),
        migrations.RemoveField(
            model_name='checkingdocumentuploaderror',
            name='checking_document_upload_id',
        ),
        migrations.AddField(
            model_name='checkingdocumentuploaderror',
            name='checking_document_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='detection.checkingdocument'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CheckingDocumentUpload',
        ),
    ]
