# Generated by Django 5.2.7 on 2025-11-01 02:59

import detection.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0017_remove_checkingdocument_checking_document_upload_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingDocumentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=detection.models.CheckingDocumentImages.checking_document_directory_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('checking_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.checkingdocument')),
            ],
        ),
    ]
