# Generated by Django 5.2.7 on 2025-11-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0018_checkingdocumentimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkingdocumentreferences',
            name='reference_text',
            field=models.CharField(max_length=50000),
        ),
        migrations.DeleteModel(
            name='CheckingDocumentSectionTokens',
        ),
    ]
