# Generated by Django 5.2.7 on 2025-11-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0019_alter_checkingdocumentreferences_reference_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkingdocumentenhancedtext',
            name='sentence_enhanced_text',
            field=models.CharField(max_length=50000),
        ),
    ]
