# Generated by Django 5.2.7 on 2025-11-05 13:58

import detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0024_alter_university_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='certificate',
            field=models.FileField(null=True, upload_to=detection.models.Instructor.certificate_directory_path),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='field',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
