# Generated by Django 5.2.7 on 2025-11-05 14:21

import detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0025_alter_instructor_certificate_alter_instructor_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='university',
            name='user',
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='Login@133613', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default='zoobaer404', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=320, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(default='Ahmad', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(default='Ahmadi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='password',
            field=models.CharField(default='Login@133613', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=320),
        ),
        migrations.AddField(
            model_name='university',
            name='password',
            field=models.CharField(default='Login@133613', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructor',
            name='certificate',
            field=models.FileField(default=1, upload_to=detection.models.Instructor.certificate_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructor',
            name='field',
            field=models.CharField(default='Computer Science', max_length=100),
            preserve_default=False,
        ),
    ]
