# Generated by Django 5.2.7 on 2025-11-08 14:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0026_remove_admin_user_remove_instructor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkingdocumenttextvector',
            name='text_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
