# Generated by Django 5.2.7 on 2025-11-09 12:49

import detection.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0027_alter_checkingdocumenttextvector_text_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingDocumentTempFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checking_document', models.FileField(upload_to=detection.models.CheckingDocumentTempFile.research_document_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checking_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.checkingdocument')),
            ],
        ),
    ]
