# Generated by Django 5.2.7 on 2025-11-10 06:57

import detection.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0028_checkingdocumenttempfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchDocumentTempFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_document', models.FileField(upload_to=detection.models.ResearchDocumentTempFile.research_document_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.researchdocument')),
            ],
        ),
    ]
